from arcade import color

SPRITE_SCALING_PLAYER = 0.1

WINDOW_SIZE = 900

CHESSBOARD_SIZE = 800

BORDER_MARGIN = (WINDOW_SIZE - CHESSBOARD_SIZE) / 2

SQUARE_SIZE = CHESSBOARD_SIZE / 8

LEFT_MARGIN = SQUARE_SIZE / 2

BOTTOM_MARGIN = SQUARE_SIZE / 2

BRIGHTER_SQUARE = color.ALICE_BLUE

DARKER_SQUARE = color.ARSENIC
